import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@machado-repo/ui/styles.css';

import enUS from './locales/en-US.json';
import esUE from './locales/es-UE.json';
import ptBR from './locales/pt-BR.json';

import "./globals.css";

import { UIProvider } from '@machado-repo/ui';
import Settings from './modules/settings';
import { getServerSession } from './modules/auth/session';
import { getAuthenticatedUserBootstrap } from './modules/auth/server';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();
  console.log('# => RootLayout => try => session => ', session)
  const { initialUser, tokenExpiresAt } = await getAuthenticatedUserBootstrap(
    session.isAuthenticated,
    session.token
  );
  console.log('# => RootLayout => try => initialUser => ', initialUser)

  const isAuthenticated = session.isAuthenticated && Boolean(initialUser);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <UIProvider locales={{ "en-US": enUS, "es-UE": esUE, "pt-BR": ptBR }}>
            <Settings isAuthenticated={isAuthenticated}>
              {children}
            </Settings>
        </UIProvider>
      </body>
    </html>
  );
}
